---
name: Bugs Reports
description: Report a bug or unexpected behavior in the project

title: "[BUG] {summary of the bug}"

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: markdown
    attributes:
      value: |
        **Expected behavior**
        A clear and concise description of what you expected to happen.

  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain your problem.

  - type: markdown
    attributes:
      value: |
        **Desktop (please complete the following information):**
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]

  - type: markdown
    attributes:
      value: |
        **Smartphone (please complete the following information):**
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context about the problem here.
---