blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
issue_templates:
  - name: New Repository Request
    about: Request to create a new empty repository
    title: "[New Repo]: "
    filename: 02-new_repo.yml
  - name: Bug Report
    about: Create a report to help us improve
    title: "[Bug]: "
    filename: 01-bug_report.yml
  - name: Feature Request
    about: Suggest an idea for this project
    title: "[Feature]: "
    filename: 03-feature_request.yml
  - name: Configuration Request
    about: Request a change to the configuration
    title: "[Config]: "
    filename: 04-config_request.yml
  - name: Documentation Request
    about: Request a change to the documentation
    title: "[Docs]: "
    filename: 05-docs_request.yml
  - name: Other
    about: For any other type of issue
    title: "[Other]: "
    filename: 06-other.yml
  - name: Security Vulnerability
    about: Report a security vulnerability
    title: "[Security]: "
    filename: 07-security_vulnerability.yml
  - name: Question
    about: Ask a question
    title: "[Question]: "
    filename: 08-question.yml
  - name: Custom
    about: Create a custom issue
    title: "[Custom]: "
    filename: 09-custom.yml
  - name: Custom 2
    about: Create a custom issue
    title: "[Custom 2]: "
    filename: 10-custom_2.yml
  - name: Custom 3
    about: Create a custom issue
    title: "[Custom 3]: "
    filename: 11-custom_3.yml
  - name: Custom 4
    about: Create a custom issue
    title: "[Custom 4]: "
    filename: 12-custom_4.yml
  - name: Custom 5
    about: Create a custom issue
    title: "[Custom 5]: "
    filename: 13-custom_5.yml
  - name: Custom 6
    about: Create a custom issue
    title: "[Custom 6]: "
    filename: 14-custom_6.yml
  - name: Custom 7
    about: Create a custom issue
    title: "[Custom 7]: "
    filename: 15