blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
issue_templates:
  - name: Bug report
    url: https://github.com/Ferskys/buildermaps/.github/ISSUE_TEMPLATE/bug_report.yml
    about: Report a bug for this project
  - name: New Repository Request
    url: https://github.com/Ferskys/buildermaps/.github/ISSUE_TEMPLATE/new_repo.yml