blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
issue_templates:
  - name: New Repository Request
    description: Request to create a new empty repository
    labels: ["new repo", "triage"]
    title: "[New Repo]: "
    body: .github/ISSUE_TEMPLATE/02-new_repo.yml